---
deployment:
  tasks:
    - export DEPLOYPATH=/home/cpanelUser/public_html/develop-announcement.ncip-hrmd.com
    - composer install
    # - /usr/local/bin/npm install
    - /bin/cp -R * $DEPLOYPATH
